name: Go

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Install and initialize dependencies
        run: |
          go get .
          echo 'The "Build Registry" step of vmware/go-ipfix ran automatically'
          echo 'See: https://github.com/vmware/go-ipfix/blob/0564a236246aa5203398a3994cd783eccae58222/README.md#build-registry'
          find /home/runner/go/

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v .
