name: Image

on: [push]

jobs:
  image:
    needs:
      - test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Build and push
        run:
          echo "Foo!"
